### ISSUE TITLE
能不能设置一个变量把左边的框宽度

### ISSUE THREAD

**Issue by supengxu** [halo-dev/halo-theme-anatole#1]
看文章的时候觉得左边太碍事了，那么大的空间

**Comment by JaneWardSandy** [comment]
在自定义样式处覆盖CSS设置的百分比即可，加起来100%
`.content,.page-top {
  width: 70% !important;
}
.sidebar {
  width: 30% !important;
}`
<img width="334" alt="image" src="https://user-images.githubusercontent.com/15345355/69302668-608f9f00-0c55-11ea-820a-3df3eefb88f9.png">



> 看文章的时候觉得左边太碍事了，那么大的空间

**Comment by ruibaby** [comment]
@JaneWardSandy 嗯 可以自定义样式

**Comment by Kherrisan** [comment]
> 在自定义样式处覆盖CSS设置的百分比即可，加起来100%
> `.content,.page-top { width: 70% !important; } .sidebar { width: 30% !important; }`
> <img alt="image" width="334" src="https://user-images.githubusercontent.com/15345355/69302668-608f9f00-0c55-11ea-820a-3df3eefb88f9.png">
> 
> > 看文章的时候觉得左边太碍事了，那么大的空间

这么写的话，好像在较窄宽度的时候，page-top 会缩短成 70%，这样 logo、title 和导航栏就不居中了。我是加了这一段：

```
@media screen and (min-width: 960px) {
.page-top { width:70% !important; }
.sidebar { width: 30% !important; }
}
```
