### ISSUE TITLE
code高亮显示有问题

### ISSUE THREAD

**Issue by womeng2009** [halo-dev/halo-theme-anatole#8]
JS的解析没问题
![image](https://user-images.githubusercontent.com/64006143/99632713-9c339380-2a78-11eb-9b62-ca88ded3d389.png)

java的不行
![image](https://user-images.githubusercontent.com/64006143/99632725-a3f33800-2a78-11eb-8fcc-e3c09473ae42.png)
其他主题正常，使用版本为最新1.2版（支持halo1.3），当前halo最新版为1.4.

**Comment by ruibaby** [comment]
目前已经更换为 highlight.js ，可以自行扩充语言。
